### ISSUE TITLE
NPE in BenchmarkPublisher.getRawResults

### ISSUE THREAD

**Issue by magik6k** [jenkinsci/benchmark-plugin#16]
When trying to execute the benchmark step, it fails with the following exception:

```java
java.lang.NullPointerException
	at org.jenkinsci.plugins.benchmark.core.BenchmarkPublisher.getRawResults(BenchmarkPublisher.java:354)
	at org.jenkinsci.plugins.benchmark.core.BenchmarkPublisher.perform(BenchmarkPublisher.java:211)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The build step:
```groovy
benchmark altInputSchema: '', altInputSchemaLocation: '', inputLocation: 'test.json', schemaSelection: 'defaultSchema', truncateStrings: false
```

`test.json` file is a static file in root of the workspace with the example result json inside (https://github.com/jenkinsci/benchmark-plugin/blob/master/doc/EXAMPLE_SCHEMA_JSON_DEFAULT.md#example-of-result-file-to-parse).

* the commit for more context: https://github.com/ipfs/go-ipfs/pull/4530/commits/826fcab29b717a9e427dbe7d39f7f18dca3dcde5
* build console: https://ci.ipfs.team/job/IPFS/job/go-ipfs/job/PR-4530/198/console (exception at the bottom)

**Comment by damercie** [comment]
Thank you for finding the issue. Will look into it.
