### ISSUE TITLE
Processing fails if Number of cores detected is 1

### ISSUE THREAD

**Issue by NickCharsley** [jenkinsci/benchmark-plugin#24]
I'm trying to use this plugin but on 2 different machines I get the following failure
`Benchmark plugin - Collection of results started.
File pattern: tracking.json
ERROR: Build step failed with exception
java.lang.ArithmeticException: / by zero
	at org.jenkinsci.plugins.benchmark.core.BenchmarkPublisher.getRawResults(BenchmarkPublisher.java:344)
	at org.jenkinsci.plugins.benchmark.core.BenchmarkPublisher.perform(BenchmarkPublisher.java:199)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:79)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Benchmark results' marked build as failure`

Digging into the code it appears that it is calculating a value of cores as 
`int cores = Runtime.getRuntime().availableProcessors() - 1;`
on these machines that is resolving to 0 and so the calculation is failing.

presumably this just needs a check for zero and then set cores=1 so the rest of the code works.

**Comment by damercie** [comment]
Good find. Will fix the initialization and return to you.

**Comment by damercie** [comment]
New version 1.0.9 was pushed and should become available inside Jenkins.

**Comment by NickCharsley** [comment]
Thanks for the quick fix :)
